version: '3.8'

services:
  nitya:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
    container_name: nitya
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - nitya_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nitya.entrypoints=websecure"
      - "traefik.http.routers.nitya.rule=Host(`nitya.geekynavigator.com`)"
      - "traefik.http.routers.nitya.tls=true"
      - "traefik.http.routers.nitya.tls.certresolver=cloudflare"
      - "traefik.http.services.nitya.loadbalancer.server.port=3000"
      - "traefik.docker.network=nitya_network"

networks:
  nitya_network:
    external: true

